# Generated by Django 4.0.3 on 2022-04-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('priority', models.CharField(choices=[('hp', 'high'), ('mp', 'medium'), ('lp', 'low')], max_length=25)),
                ('effort', models.CharField(choices=[('he', 'high'), ('me', 'medium'), ('le', 'low')], max_length=25)),
                ('status', models.CharField(choices=[('0', 'To-do'), ('1', 'Done')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
